### ISSUE TITLE
Problem deleting queries

### ISSUE THREAD

**Issue by alkalir** [alkalir/MONICA_tool#1]
Hi, 
when I delete an old query (already stored), the tool comes back to the latest query available. However, I get the screen attached (it seems that parameters do not load correctly). After a refresh, they reload correctly.
![Cattura](https://user-images.githubusercontent.com/12234084/115240438-0895ea00-a120-11eb-8c49-542253484f2c.PNG)

**Comment by temuccio** [comment]
Commit 5999b37 should solve this issue.
